### PR TITLE
Simplifies ParamExtractor get_parameters() method with RegExp

### PR DESCRIPTION
**Pull request by markre94**
Hi! I've been using your library from quite some time and was wondering if I could contribute with something. I have an idea which would simplify an area of your code (marked as #TODO). 

So I've noticed that ParameterExtractor  -> get_parameters() contains a logic for parsing `'{param}'` from the input xpath string. I've manage to get this effect using regular expressions. All tests are passing, I've also added 2 new ones.

Looking forward for your feedback.

### CODE REVIEW

**Review by bigSAS — APPROVED** [review]
dzieki za wklad w libke 🍺

**Comment by bigSAS** [comment]
image
:)

**Comment by markre94** [comment]
Git :). Można się z Tobą jakoś skontaktować? Interesuje mnie Twoja prelekcja z talk4devs ale nie mogę znaleźć tego na yt. Jest to jeszcze gdzieś dostępne?

**Comment by bigSAS** [comment]
tmajk@saskodzi.pl ;)

**Pull request merged**
